### ISSUE TITLE
--fix support

### ISSUE THREAD

**Issue by debuglebowski** [KyleMayes/eslint-plugin-ordered-imports#12]
Nice job so far with this plugin! I like how you have structured the configuration and the linting seems to work so far for me.

However, the --fix flag doesn't work for me. Is this implemented yet?

I use version 0.4.0.

**Comment by KyleMayes** [comment]
This plugin provides fixes for reordering unsorted imports *within* an import group (see [here](https://github.com/KyleMayes/eslint-plugin-ordered-imports/blob/21976922dad14d55ba1c3c97d7e3e22140b56cb0/src/rule.spec.ts#L320-L341) for a test case demonstrating this) but it does not currently provide fixes for problems relating to import groups:

* Import in the wrong import group
* Import groups in the wrong order
* Unmerged import groups

Is this one of the things you were hoping would be automatically fixed? Or do you have an example of this plugin failing to reorder imports within an import group?

The latter would be a bug, but the former would be the expected behavior (but I might take another crack at implementing fixes for import group problems, I remember it was harder than I thought it would be which is why it was never implemented).

**Comment by debuglebowski** [comment]
Ah, I see. Thanks for clarifying! 💯 I did not get this from the documentation (something you might want to add).

The functionality I'm looking for is what you are describing - a way to sorting groups themselves rather than sorting within the groups. So as far I'm I know, it works as intended :)
