### ISSUE TITLE
Remove unnecessary files from package

### ISSUE THREAD

**Issue by krisztianb** [KyleMayes/eslint-plugin-ordered-imports#7]
Hi Kyle,

your [package.json](https://github.com/KyleMayes/eslint-plugin-ordered-imports/blob/master/package.json) uses the `files` object to define which directories and files should be included in the NPM package:

```JS
"files": [
    "dist",
    "src",
    "input.json"
  ]
```

The way I see it the `src` (source files) entry is not needed. People who install your package don't need the TypeScript source code. They can find the source code here on Github if they need it.

I don't know about the `input.json` file. It is not up here on Github. What is that used for?

**Comment by KyleMayes** [comment]
Fixed in `v0.3.1`.

The `input.json` file is a JSON schema [generated](https://github.com/KyleMayes/eslint-plugin-ordered-imports/blob/e1278401aaefa3a9a71ae375aae5946e74be93fb/package.json#L16) from the [TypeScript type which represents the rule options](https://github.com/KyleMayes/eslint-plugin-ordered-imports/blob/e1278401aaefa3a9a71ae375aae5946e74be93fb/src/options.ts#L28). This way I can [use the TypeScript type as the ESLint rule schema](https://github.com/KyleMayes/eslint-plugin-ordered-imports/blob/e1278401aaefa3a9a71ae375aae5946e74be93fb/src/rule.ts#L9) without having to duplicate effort.
